{
  imports = [
    ./avante.nix
    ./blink.nix
    ./bufferline.nix
    ./conform.nix
    ./copilot.nix
    ./flash.nix
    ./gitsigns.nix
    ./grug-far.nix
    ./harpoon.nix
    ./incline.nix
    ./lazydev.nix
    ./lint.nix
    ./lspconfig.nix
    ./lualine.nix
    ./mini-ai.nix
    ./mini-icons.nix
    ./mini-pairs.nix
    ./mini-surround.nix
    ./neo-tree.nix
    ./noice.nix
    ./nui.nix
    ./nvim-tmux-navigation.nix
    ./oil.nix
    ./persistence.nix
    ./snacks.nix
    ./telescope.nix
    ./theme.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./treesj.nix
    ./trouble.nix
    ./ts-comments.nix
    ./which-key.nix
  ];
}
